#!/usr/bin/env bash
# Fetch a CC0 Polyglot opening book (Lichess games, generated by jja) and
# install it as books/book.bin.
#
# Usage: scripts/fetch_book.sh [book.zst]
#   Default: lichess-201301-202303-gm2600.bin.zst
#   Others : lichess-201301-202303-2800+.bin.zst, lichess-201301-202303-magnus.bin.zst
#
# The books are released under CC0 (see https://www.chesswob.org/jja/books/),
# compatible with this GPLv3 project. The .bin is NOT committed.
set -euo pipefail

BASE="https://www.chesswob.org/jja/books"
BOOK="${1:-lichess-201301-202303-gm2600.bin.zst}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/books/book.bin"

command -v curl >/dev/null || { echo "curl is required" >&2; exit 1; }
command -v zstd >/dev/null || { echo "zstd is required" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Downloading $BASE/$BOOK ..."
curl -fsSL "$BASE/$BOOK" -o "$TMP/book.zst"

echo "Decompressing -> $OUT"
zstd -d -f "$TMP/book.zst" -o "$OUT" >/dev/null

echo "Book ready: $OUT ($(du -h "$OUT" | cut -f1), $(( $(stat -c%s "$OUT") / 16 )) entries)"
